name: Calculate Euro 2024

on:
  workflow_run:
    workflows: ["JSON Generation"]
    types:
      - completed

jobs:
  json_gen:
    runs-on: ubuntu-latest

    steps:
      - name: Check the previous workflow
        run: |
          if [ ${{ github.event.workflow_run.conclusion == 'success' }} ]; then
            echo "Previous workflow OK"  
          else
            echo "Previous workflow in error"
            exit 1
          fi
          
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Euro 2024 Scripts
        run: |
          echo "Working Directory: $(pwd)"
          echo "Files in Current Directory: $(ls -al)"
          python scripts/040_Competitions/0400_Euro2024/0401_Calculate_Insert_Euro2024.py
          python scripts/040_Competitions/0400_Euro2024/0402_Generate_JSON_Euro2024.py

      - name: Commit changes
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          if git diff --quiet -- data; then
            echo "No changes in data directory. Skipping commit."
          else
            git add -A data
            git commit -m "Update euro2024 data"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
