name: JSON Generation
on:
  push:
    branches:
      - main

jobs:
  init_db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run JSON generation script
        run: |
          echo "Working Directory: $(pwd)"
          echo "Files in Current Directory: $(ls -al)"
          python scripts/json_generation.py

      - name: Commit changes
        run: |
            git config --global user.email "c.bravo2@yahoo.fr"
            git config --global user.name "16bravo"
            git add data/LastMonthRanking.json
            git commit -m "Update LastMonthRanking.json"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}