name: JSON Generation
on:
  push:
    branches:
      - main

jobs:
  init_db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run JSON generation script
        run: |
          echo "Working Directory: $(pwd)"
          echo "Files in Current Directory: $(ls -al)"
          python scripts/json_generation.py