name: DB Initialisation

on:
  push:
    branches:
      - main

jobs:
  init_db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Kaggle credentials
        run: echo "$KAGGLE_JSON" > /home/runner/.kaggle/kaggle.json && chmod 600 /home/runner/.kaggle/kaggle.json

      - name: Run initialization script
        run: python scripts/db_initialisation.py
        env:
          KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}